# Generated by Django 5.1.3 on 2024-12-10 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='publicada',
            new_name='publicado',
        ),
    ]
